/**
 * Russian names for daily-learning readings, keyed by the exact English keys
 * used by `@hebcal/learning` data (which mixes Ashkenazi spellings in the
 * Bavli list — "Berachot", "Baba Kamma" — with Sephardic spellings in the
 * Mishna/Yerushalmi lists — "Berakhot", "Bava Kamma"; both variants are keys
 * here). English falls through to the hebcal key itself and Hebrew comes from
 * the package's own `he.po` catalog, so only Russian is maintained by hand —
 * same pattern as `src/lib/calendar/holidays-ru.ts`.
 *
 * Tractates and Tanach books use the transliteration style shared with the
 * companion zmanim_bot project; Rambam (Mishneh Torah) sections use the
 * conventional translated «Законы …» titles.
 *
 * A unit test enumerates every name reachable from each cycle and fails if a
 * key is missing here, so this table can't silently go stale.
 */
export const LEARNING_NAMES_RU: Record<string, string> = {
  // Talmud Bavli tractates (Daf Yomi spellings)
  Berachot: 'Брахот',
  Shabbat: 'Шабат',
  Eruvin: 'Эрувин',
  Pesachim: 'Псахим',
  Shekalim: 'Шкалим',
  Yoma: 'Йома',
  Sukkah: 'Сукка',
  Beitzah: 'Бейца',
  'Rosh Hashana': 'Рош а-Шана',
  Taanit: 'Таанит',
  Megillah: 'Мегила',
  'Moed Katan': 'Моэд катан',
  Chagigah: 'Хагига',
  Yevamot: 'Йевамот',
  Ketubot: 'Ктубот',
  Nedarim: 'Недарим',
  Nazir: 'Назир',
  Sotah: 'Сота',
  Gitin: 'Гитин',
  Kiddushin: 'Кидушин',
  'Baba Kamma': 'Бава кама',
  'Baba Metzia': 'Бава мециа',
  'Baba Batra': 'Бава батра',
  Sanhedrin: 'Санхедрин',
  Makkot: 'Макот',
  Shevuot: 'Швуот',
  'Avodah Zarah': 'Авода зара',
  Horayot: 'Орайот',
  Zevachim: 'Звахим',
  Menachot: 'Менахот',
  Chullin: 'Хулин',
  Bechorot: 'Бехорот',
  Arachin: 'Арахин',
  Temurah: 'Тмура',
  Keritot: 'Критот',
  Meilah: 'Меила',
  Kinnim: 'Киним',
  Tamid: 'Тамид',
  Midot: 'Мидот',
  Niddah: 'Нида',

  // Mishna / Yerushalmi spelling variants and Mishna-only tractates
  Berakhot: 'Брахот',
  Peah: 'Пеа',
  Demai: 'Дмай',
  Kilayim: 'Килаим',
  Sheviit: 'Швиит',
  Terumot: 'Трумот',
  Maasrot: 'Маасрот',
  'Maaser Sheni': 'Маасер шени',
  Challah: 'Хала',
  Orlah: 'Орла',
  Bikkurim: 'Бикурим',
  'Rosh Hashanah': 'Рош а-Шана',
  Gittin: 'Гитин',
  'Bava Kamma': 'Бава кама',
  'Bava Metzia': 'Бава мециа',
  'Bava Batra': 'Бава батра',
  Eduyot: 'Эдуйот',
  Avot: 'Авот',
  Bekhorot: 'Бехорот',
  Arakhin: 'Арахин',
  Middot: 'Мидот',
  Kelim: 'Келим',
  Oholot: 'Оолот',
  Negaim: 'Негаим',
  Parah: 'Пара',
  Tahorot: 'Таарот',
  Mikvaot: 'Микваот',
  Makhshirin: 'Махширин',
  Zavim: 'Завим',
  'Tevul Yom': 'Твуль йом',
  Yadayim: 'Ядаим',
  Oktzin: 'Укцин',

  // Nach Yomi books
  Joshua: 'Йеошуа',
  Judges: 'Шофтим',
  'I Samuel': 'Шмуэль I',
  'II Samuel': 'Шмуэль II',
  'I Kings': 'Млахим I',
  'II Kings': 'Млахим II',
  Isaiah: 'Йешаяу',
  Jeremiah: 'Ирмияу',
  Ezekiel: 'Йехезкель',
  Hosea: 'Ошеа',
  Joel: 'Йоэль',
  Amos: 'Амос',
  Obadiah: 'Овадья',
  Jonah: 'Йона',
  Micah: 'Миха',
  Nachum: 'Нахум',
  Habakkuk: 'Хавакук',
  Zephaniah: 'Цфанья',
  Haggai: 'Хагай',
  Zechariah: 'Зхарья',
  Malachi: 'Малахи',
  Psalms: 'Теилим',
  Proverbs: 'Мишлей',
  Job: 'Ийов',
  'Song of Songs': 'Шир а-ширим',
  Ruth: 'Рут',
  Lamentations: 'Эйха',
  Ecclesiastes: 'Коэлет',
  Esther: 'Эстер',
  Daniel: 'Даниэль',
  Ezra: 'Эзра',
  Nehemiah: 'Нехемья',
  'I Chronicles': 'Диврей а-ямим I',
  'II Chronicles': 'Диврей а-ямим II',

  // Daily Rambam (Mishneh Torah) — Sefer HaMitzvot intro readings
  'Transmission of the Oral Law': 'Передача Устной Торы',
  'Positive Mitzvot': 'Предписывающие заповеди',
  'Negative Mitzvot': 'Запрещающие заповеди',
  'Overview of Mishneh Torah Contents': 'Обзор содержания «Мишне Тора»',

  // Daily Rambam (Mishneh Torah) sections
  'Foundations of the Torah': 'Законы основ Торы',
  'Human Dispositions': 'Законы о чертах характера',
  'Torah Study': 'Законы изучения Торы',
  'Foreign Worship and Customs of the Nations': 'Законы об идолопоклонстве',
  Repentance: 'Законы раскаяния',
  'Reading the Shema': 'Законы чтения «Шма»',
  'Prayer and the Priestly Blessing': 'Законы молитвы и благословения коэнов',
  'Tefillin, Mezuzah and the Torah Scroll': 'Законы тфилин, мезузы и свитка Торы',
  Fringes: 'Законы цицит',
  Blessings: 'Законы благословений',
  Circumcision: 'Законы обрезания',
  'The Order of Prayer': 'Порядок молитвы',
  Sabbath: 'Законы субботы',
  'Rest on the Tenth of Tishrei': 'Законы покоя десятого тишрея',
  'Rest on a Holiday': 'Законы покоя в праздники',
  'Leavened and Unleavened Bread': 'Законы о хамце и маце',
  'Shofar, Sukkah and Lulav': 'Законы шофара, сукки и лулава',
  'Sheqel Dues': 'Законы о шекелях',
  'Sanctification of the New Month': 'Законы освящения месяца',
  Fasts: 'Законы постов',
  'Scroll of Esther and Hanukkah': 'Законы свитка Эстер и Хануки',
  Marriage: 'Законы брака',
  Divorce: 'Законы развода',
  'Levirate Marriage and Release': 'Законы левиратного брака и халицы',
  'Virgin Maiden': 'Законы о девушке',
  'Woman Suspected of Infidelity': 'Законы о соте',
  'Forbidden Intercourse': 'Законы запрещённых связей',
  'Forbidden Foods': 'Законы запрещённой пищи',
  'Ritual Slaughter': 'Законы шхиты',
  Oaths: 'Законы клятв',
  Vows: 'Законы обетов',
  Nazariteship: 'Законы назорейства',
  'Appraisals and Devoted Property': 'Законы оценок и посвящений',
  'Diverse Species': 'Законы килаим',
  'Gifts to the Poor': 'Законы даров бедным',
  'Heave Offerings': 'Законы трумот',
  Tithes: 'Законы десятин',
  "Second Tithes and Fourth Year's Fruit": 'Законы второй десятины и плодов четвёртого года',
  'First Fruits and other Gifts to Priests Outside the Sanctuary': 'Законы бикурим и других даров коэнам',
  'Sabbatical Year and the Jubilee': 'Законы седьмого и юбилейного годов',
  'The Chosen Temple': 'Законы Храма',
  'Vessels of the Sanctuary and Those who Serve Therein': 'Законы храмовой утвари и служащих в Храме',
  'Admission into the Sanctuary': 'Законы входа в Храм',
  'Things Forbidden on the Altar': 'Законы о запрещённом для жертвенника',
  'Sacrificial Procedure': 'Законы совершения жертвоприношений',
  'Daily Offerings and Additional Offerings': 'Законы постоянных и дополнительных жертв',
  'Sacrifices Rendered Unfit': 'Законы о непригодных жертвах',
  'Service on the Day of Atonement': 'Законы служения в Йом Кипур',
  Trespass: 'Законы о меиле',
  'Paschal Offering': 'Законы пасхальной жертвы',
  'Festival Offering': 'Законы праздничной жертвы',
  Firstlings: 'Законы о первенцах',
  'Offerings for Unintentional Transgressions': 'Законы жертв за неумышленные грехи',
  'Offerings for Those with Incomplete Atonement': 'Законы о жертвах для завершения искупления',
  Substitution: 'Законы тмуры',
  'Defilement by a Corpse': 'Законы нечистоты от мёртвого',
  'Red Heifer': 'Законы красной коровы',
  'Defilement by Leprosy': 'Законы нечистоты цараат',
  'Those Who Defile Bed or Seat': 'Законы оскверняющих ложе и сиденье',
  'Other Sources of Defilement': 'Законы прочих источников нечистоты',
  'Defilement of Foods': 'Законы нечистоты пищи',
  Vessels: 'Законы сосудов',
  'Immersion Pools': 'Законы миквы',
  'Damages to Property': 'Законы имущественного ущерба',
  Theft: 'Законы о краже',
  'Robbery and Lost Property': 'Законы о грабеже и потерях',
  'One Who Injures a Person or Property': 'Законы о нанесении ущерба человеку или имуществу',
  'Murderer and the Preservation of Life': 'Законы об убийце и сохранении жизни',
  Sales: 'Законы продажи',
  'Ownerless Property and Gifts': 'Законы о бесхозном имуществе и дарах',
  Neighbors: 'Законы соседей',
  'Agents and Partners': 'Законы о посланцах и компаньонах',
  Slaves: 'Законы о рабах',
  Hiring: 'Законы найма',
  'Borrowing and Deposit': 'Законы одалживания и хранения',
  'Creditor and Debtor': 'Законы кредитора и должника',
  'Plaintiff and Defendant': 'Законы истца и ответчика',
  Inheritances: 'Законы наследования',
  'The Sanhedrin and the Penalties within their Jurisdiction': 'Законы Санхедрина и наказаний',
  Testimony: 'Законы свидетельства',
  Rebels: 'Законы о непокорных',
  Mourning: 'Законы траура',
  'Kings and Wars': 'Законы царей и войн',
};
