export const DEFAULT_COORDS = {
  LAT: 32.109333,
  LNG: 34.855499,
};

export const ZMANIM_KEYS = [
  'BeginAstronomicalTwilight',
  'AlosHashachar',
  'Alos72',
  'BeginNauticalTwilight',
  'BeginCivilTwilight',
  'SeaLevelSunrise',
  'Sunrise',
  'SofZmanShmaMGA',
  'SofZmanShmaGRA',
  'SofZmanTfilaMGA',
  'SofZmanTfilaGRA',
  'Chatzos',
  'SunTransit',
  'MinchaGedola',
  'MinchaKetana',
  'PlagHamincha',
  'CandleLighting',
  'SeaLevelSunset',
  'Sunset',
  'EndCivilTwilight',
  'Tzais',
  'EndNauticalTwilight',
  'Tzais72',
  'EndAstronomicalTwilight',
  'ShaahZmanisGra',
  'TemporalHour',
  'ShaahZmanisMGA',
];
