import { Parsha } from 'kosher-zmanim';

/**
 * Russian transliterations of the parshiyos, keyed by kosher-zmanim's `Parsha`
 * enum. kosher-zmanim ships only Ashkenazi-English and Hebrew lists, so for the
 * `ru` locale we install this map via `HebrewDateFormatter.setTransliteratedParshiosList`
 * (see `createHebrewFormatter`). English/Hebrew keep the formatter's own output.
 *
 * The map must cover every `Parsha` member (including the double parshiyos and
 * the special Shabbasos) — `setTransliteratedParshiosList` expects a complete
 * `Record<Parsha, string>`. Terminology mirrors the companion `zmanim_bot`.
 */
export const RU_PARSHIYOS: Record<Parsha, string> = {
  [Parsha.NONE]: '',
  [Parsha.BERESHIS]: 'Берешит',
  [Parsha.NOACH]: 'Ноах',
  [Parsha.LECH_LECHA]: 'Лех-Леха',
  [Parsha.VAYERA]: 'Ваейра',
  [Parsha.CHAYEI_SARA]: 'Хаей Сара',
  [Parsha.TOLDOS]: 'Толдот',
  [Parsha.VAYETZEI]: 'Ваеце',
  [Parsha.VAYISHLACH]: 'Ваишлах',
  [Parsha.VAYESHEV]: 'Ваешев',
  [Parsha.MIKETZ]: 'Микец',
  [Parsha.VAYIGASH]: 'Ваигаш',
  [Parsha.VAYECHI]: 'Вайехи',
  [Parsha.SHEMOS]: 'Шемот',
  [Parsha.VAERA]: 'Ваэра',
  [Parsha.BO]: 'Бо',
  [Parsha.BESHALACH]: 'Бешалах',
  [Parsha.YISRO]: 'Итро',
  [Parsha.MISHPATIM]: 'Мишпатим',
  [Parsha.TERUMAH]: 'Трума',
  [Parsha.TETZAVEH]: 'Тецаве',
  [Parsha.KI_SISA]: 'Ки Тиса',
  [Parsha.VAYAKHEL]: 'Ваякхель',
  [Parsha.PEKUDEI]: 'Пкудей',
  [Parsha.VAYIKRA]: 'Ваикра',
  [Parsha.TZAV]: 'Цав',
  [Parsha.SHMINI]: 'Шмини',
  [Parsha.TAZRIA]: 'Тазриа',
  [Parsha.METZORA]: 'Мецора',
  [Parsha.ACHREI_MOS]: 'Ахарей Мот',
  [Parsha.KEDOSHIM]: 'Кдошим',
  [Parsha.EMOR]: 'Эмор',
  [Parsha.BEHAR]: 'Беар',
  [Parsha.BECHUKOSAI]: 'Бехукотай',
  [Parsha.BAMIDBAR]: 'Бемидбар',
  [Parsha.NASSO]: 'Насо',
  [Parsha.BEHAALOSCHA]: 'Беаалотха',
  [Parsha.SHLACH]: 'Шлах',
  [Parsha.KORACH]: 'Корах',
  [Parsha.CHUKAS]: 'Хукат',
  [Parsha.BALAK]: 'Балак',
  [Parsha.PINCHAS]: 'Пинхас',
  [Parsha.MATOS]: 'Матот',
  [Parsha.MASEI]: 'Масей',
  [Parsha.DEVARIM]: 'Дварим',
  [Parsha.VAESCHANAN]: 'Ваэтханан',
  [Parsha.EIKEV]: 'Экев',
  [Parsha.REEH]: 'Реэ',
  [Parsha.SHOFTIM]: 'Шофтим',
  [Parsha.KI_SEITZEI]: 'Ки Теце',
  [Parsha.KI_SAVO]: 'Ки Таво',
  [Parsha.NITZAVIM]: 'Ницавим',
  [Parsha.VAYEILECH]: 'Ваелех',
  [Parsha.HAAZINU]: 'Аазину',
  [Parsha.VZOS_HABERACHA]: 'Везот а-Браха',
  [Parsha.VAYAKHEL_PEKUDEI]: 'Ваякхель-Пкудей',
  [Parsha.TAZRIA_METZORA]: 'Тазриа-Мецора',
  [Parsha.ACHREI_MOS_KEDOSHIM]: 'Ахарей Мот-Кдошим',
  [Parsha.BEHAR_BECHUKOSAI]: 'Беар-Бехукотай',
  [Parsha.CHUKAS_BALAK]: 'Хукат-Балак',
  [Parsha.MATOS_MASEI]: 'Матот-Масей',
  [Parsha.NITZAVIM_VAYEILECH]: 'Ницавим-Ваелех',
  [Parsha.SHKALIM]: 'Шкалим',
  [Parsha.ZACHOR]: 'Захор',
  [Parsha.PARA]: 'Пара',
  [Parsha.HACHODESH]: 'а-Ходеш',
  [Parsha.SHUVA]: 'Шува',
  [Parsha.SHIRA]: 'Шира',
  [Parsha.HAGADOL]: 'а-Гадоль',
  [Parsha.CHAZON]: 'Хазон',
  [Parsha.NACHAMU]: 'Нахаму',
};
